=== margaritovamariya/XML-project/Проект/1. Част/fitness.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT gym (hall*)>
<!ELEMENT hall (id, name, note?, male_allowed, female_allowed, has_wc, has_ac, number_of_equipments, equipment*, training)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT male_allowed (#PCDATA)>
<!ELEMENT female_allowed (#PCDATA)>
<!ELEMENT has_wc (#PCDATA)>
<!ELEMENT has_ac (#PCDATA)>
<!ELEMENT number_of_equipments (#PCDATA)>
<!ELEMENT equipment (name, min_kg, max_kg, current_kg)>
<!ELEMENT min_kg (#PCDATA)>
<!ELEMENT max_kg (#PCDATA)>
<!ELEMENT current_kg (#PCDATA)>
<!ELEMENT training (length, is_group, number_of_people?, calories_burnt, pace, number_of_breaks, break_length)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT is_group (#PCDATA)>
<!ELEMENT number_of_people (#PCDATA)>
<!ELEMENT calories_burnt (#PCDATA)>
<!ELEMENT pace (#PCDATA)>
<!ELEMENT number_of_breaks (#PCDATA)>
<!ELEMENT break_length (#PCDATA)>

<!ATTLIST hall open (да | не) "да">
<!ATTLIST hall group_training_allowed (да | не) "да">
<!ATTLIST equipment type (машина | тежести) "тежести">
<!ATTLIST equipment machine_type (бутаща | дърпаща) "бутаща">
<!ATTLIST training type (долна_част | горна_част | кардио | цяло_тяло | корем) #REQUIRED>

=== margaritovamariya/XML-project/Проект/2. Част/valid_xml3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE gym SYSTEM "fitness.dtd">

<gym>
  <hall open="да" group_training_allowed="да">
    <id>3</id>
    <name>Зала за Групови Уроци</name>
    <note>Резервирана за групови занимания</note>
    <male_allowed>да</male_allowed>
    <female_allowed>да</female_allowed>
    <has_wc>да</has_wc>
    <has_ac>да</has_ac>
    <number_of_equipments>15</number_of_equipments>
    <equipment type="тежести">
      <name>Штанга</name>
      <min_kg>10</min_kg>
      <max_kg>50</max_kg>
      <current_kg>20</current_kg>
    </equipment>
    <training type="цяло_тяло">
      <length>75</length>
      <is_group>да</is_group>
      <number_of_people>15</number_of_people>
      <calories_burnt>500</calories_burnt>
      <pace>средно</pace>
      <number_of_breaks>3</number_of_breaks>
      <break_length>7</break_length>
    </training>
  </hall>
</gym>

=== margaritovamariya/XML-project/Проект/1. Част/proba.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE gym SYSTEM "fitness.dtd">

<gym>
	<hall open="да" group_training_allowed="да">
		<id>1</id>
		<name>Главна зала</name>
		<note>Просторна зала с естествена светлина</note>
		<male_allowed>да</male_allowed>
		<female_allowed>да</female_allowed>
		<has_wc>да</has_wc>
		<has_ac>да</has_ac>
		<number_of_equipments>10</number_of_equipments>
		<equipment type="тежести">
			<name>Дъмбели</name>
			<min_kg>5</min_kg>
			<max_kg>50</max_kg>
			<current_kg>10</current_kg>
		</equipment>
		<training type="цяло_тяло">
			<length>60</length>
			<is_group>не</is_group>
			<calories_burnt>300</calories_burnt>
			<pace>средно</pace>
			<number_of_breaks>2</number_of_breaks>
			<break_length>5</break_length>
		</training>
	</hall>
</gym>

=== margaritovamariya/XML-project/Проект/2. Част/valid_xml2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE gym SYSTEM "fitness.dtd">

<gym>
  <hall open="да" group_training_allowed="да">
    <id>2</id>
    <name>Зала за Кардио</name>
    <male_allowed>да</male_allowed>
    <female_allowed>да</female_allowed>
    <has_wc>да</has_wc>
    <has_ac>да</has_ac>
    <number_of_equipments>20</number_of_equipments>
    <equipment type="машина" machine_type="бутаща">
      <name>Лентов Тротоар</name>
      <min_kg>5</min_kg>
      <max_kg>15</max_kg>
      <current_kg>10</current_kg>
    </equipment>
    <training type="кардио">
      <length>45</length>
      <is_group>не</is_group>
      <calories_burnt>400</calories_burnt>
      <pace>висок</pace>
      <number_of_breaks>1</number_of_breaks>
      <break_length>3</break_length>
    </training>
  </hall>
</gym>

=== margaritovamariya/XML-project/Проект/2. Част/valid_xml4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE gym SYSTEM "fitness.dtd">

<gym>
  <hall open="да" group_training_allowed="да">
    <id>5</id>
    <name>Зала без Климатик</name>
    <male_allowed>да</male_allowed>
    <female_allowed>да</female_allowed>
    <has_wc>да</has_wc>
    <has_ac>не</has_ac>
    <number_of_equipments>12</number_of_equipments>
    <equipment type="тежести">
      <name>Кетълбел</name>
      <min_kg>5</min_kg>
      <max_kg>20</max_kg>
      <current_kg>12</current_kg>
    </equipment>
    <training type="цяло_тяло">
      <length>60</length>
      <is_group>не</is_group>
      <calories_burnt>350</calories_burnt>
      <pace>средно</pace>
      <number_of_breaks>2</number_of_breaks>
      <break_length>5</break_length>
    </training>
  </hall>
</gym>

=== margaritovamariya/XML-project/Проект/2. Част/valid_xml5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE gym SYSTEM "fitness.dtd">

<gym>
  <hall open="да" group_training_allowed="не">
    <id>4</id>
    <name>Зона за Тежка Атлетика</name>
    <male_allowed>да</male_allowed>
    <female_allowed>не</female_allowed>
    <has_wc>да</has_wc>
    <has_ac>не</has_ac>
    <number_of_equipments>8</number_of_equipments>
    <equipment type="тежести">
      <name>Пауър Рак</name>
      <min_kg>20</min_kg>
      <max_kg>200</max_kg>
      <current_kg>50</current_kg>
    </equipment>
    <training type="горна_част">
      <length>90</length>
      <is_group>не</is_group>
      <calories_burnt>600</calories_burnt>
      <pace>бавно</pace>
      <number_of_breaks>2</number_of_breaks>
      <break_length>8</break_length>
    </training>
  </hall>
</gym>
